version: "3.5"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: robin
      POSTGRES_PASSWORD: R0bin!
      POSTGRES_DB: openfisher
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 8080:8080
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres:
